Add Event Trigger for Infinite Fuel Toggle
TomGrobbe/vMenu pull request #270
Opened 2021-12-26 17:08 UTC by coleminer0112

Allows custom fuel resources to watch for infinite fuel in vMenu

2021-12-26 17:23 UTC, MichaelCoding25 commented
I'm pretty sure you also need to register the event, so people can just AddEventHandler to it in their script.

2021-12-26 19:59 UTC, coleminer0112 commented
> I'm pretty sure you also need to register the event, so people can just AddEventHandler to it in their script.

It doesn't require registering unless it's going across the Net, which it isn't - it is a client side only event

2022-05-05 20:34 UTC, TomGrobbe commented
I have a suggestion for an additional change, that'd make this more useful, whenever the resource loads and it sets the original value form the saved preferences, it should trigger the event once so your other resource has a chance of knowing what the status is once a player joins and doesn't toggle it manually. Or exposing an export function that gets the current value.

2022-05-05 20:34 UTC, TomGrobbe commented
Other than that it's a useful feature

2023-03-04 17:10 UTC, TomGrobbe commented
Could you rebase your changes based on the latest `development` branch and resolve the conflicts please?

2023-03-04 17:11 UTC, TomGrobbe requested changes
Comments need to be resolved

2023-03-07 22:21 UTC, coleminer0112 commented
> I have a suggestion for an additional change, that'd make this more useful, whenever the resource loads and it sets the original value form the saved preferences, it should trigger the event once so your other resource has a chance of knowing what the status is once a player joins and doesn't toggle it manually. Or exposing an export function that gets the current value.

The current development version has no userDefault for this setting, so it may not be necessary to do an initial check!

Also, I rebased, but I am not a Git-master... so I am unsure why it is now 3 commits despite only the 1 change.

2025-03-21 00:24 UTC, XdGoldenTigerOfficial approved these changes

2025-03-21 00:27 UTC, merged